#!/bin/sh
update-rc.d decades defaults >/dev/null
invoke-rc.d decades start
# Automatically added by dh_installinit
if [ -x "/etc/init.d/decades" ]; then
	if [ ! -e "/etc/init/decades.conf" ]; then
		update-rc.d decades defaults >/dev/null
	fi
	invoke-rc.d decades start || exit $?
fi
# End automatically added section

