#!/bin/sh
update-rc.d decades defaults >/dev/null
# Automatically added by dh_installinit
if [ -x "/etc/init.d/decades" ]; then
	if [ ! -e "/etc/init/decades.conf" ]; then
		update-rc.d decades defaults >/dev/null
	fi
	invoke-rc.d decades start || exit $?
fi
# End automatically added section

# Automatically added by dh_python2:
if which pycompile >/dev/null 2>&1; then
	pycompile -p decades 
fi

# End automatically added section

