#!/bin/sh
invoke-rc.d decades stop
# Automatically added by dh_installinit
if [ -x "/etc/init.d/decades" ]; then
	invoke-rc.d decades stop || exit $?
fi
# End automatically added section

# Automatically added by dh_python2:
if which pyclean >/dev/null 2>&1; then
	pyclean -p decades 
else
	dpkg -L decades | grep \.py$ | while read file
	do
		rm -f "${file}"[co] >/dev/null
  	done
fi

# End automatically added section

